/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.ceragon;

import java.io.BufferedInputStream;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.io.Writer;
import java.io.FileWriter;
import java.nio.file.Files;

import org.gradle.testkit.runner.GradleRunner;
import org.gradle.testkit.runner.BuildResult;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
 * A simple functional test for the 'io.github.ceragon.proto' plugin.
 */
class GradlePluginPluginFunctionalTest {
    @Test void canRunTask() throws IOException {
        // Setup the test build
        File projectDir = new File("build/functionalTest");
        Files.createDirectories(projectDir.toPath());
        writeString(new File(projectDir, "settings.gradle"), "");
        InputStream inputStream = GradlePluginPluginFunctionalTest.class.getResourceAsStream("/build.gradle");
        try (BufferedInputStream bufferedInputStream = new BufferedInputStream(inputStream);
             ){
            StringBuilder builder = new StringBuilder();
            byte[] data = new byte[1024];
            int length;
            while((length = bufferedInputStream.read(data)) > 0){
                builder.append(new String(data,0,length));
            }
            writeString(new File(projectDir, "build.gradle"), builder.toString());
        }


        // Run the build
        GradleRunner runner = GradleRunner.create();
        runner.forwardOutput();
        runner.withPluginClasspath();
        runner.withArguments("proto");
        runner.withProjectDir(projectDir);
        BuildResult result = runner.build();

        // Verify the result
        assertTrue(result.getOutput().contains("BUILD SUCCESSFUL "));
    }

    private void writeString(File file, String string) throws IOException {
        try (Writer writer = new FileWriter(file)) {
            writer.write(string);
        }
    }
}
